Update image_utils.py
I still don't entirely have an explanation for this, but when I ran eden within docker, the client script that was working fine locally started running into the following error when the IP was changed to the container's address:

```
File "/home/eden/.local/lib/python3.10/site-packages/eden/datatypes.py", line 33, in __init__
    self.data = encode(image)
  File "/home/eden/.local/lib/python3.10/site-packages/eden/image_utils.py", line 41, in encode
    or isinstance(
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

`eden-python` was installed with `pip` in the docker image. When I sent a request to the container, I was getting "failed" statuses, and the logs of the container contained the error above printed to `stdout` (I set `logfile=None` in my `server.py`).

I added the proposed modified `image_utils.py` file into the build as a test for this change and consistently started getting "complete" statuses:
```
COPY image_utils.py /home/eden/.local/lib/python3.10/site-packages/eden/image_utils.py
```